mysql:
  host: localhost
  port: 3306
  db: markBlog
  user: root
  password: root
  config: '?charset=utf8&parseTime=true&loc=Local'
  log_level: dev

logger:
  level: info 
  prefix: '[markBlog]'
  director: log
  show_line: true
  log_in_console: true


system:
  host: 0.0.0.0
  port: 9999
  env: release


email:
  account: "2247654142@qq.com"
  password: "dzysmsmuyoptebfe"
  port: 587
  host: "smtp.qq.com"

